# https://taskfile.dev

version: '3'

tasks:
  edit:
    desc: edit game project
    cmds:
      - bin/task.64 unzip:godot
      - bin/godot_x11.64 game/project.godot

  gut:
    desc: run gut project using headless
    cmds:
      - bin/task.64 unzip:godot:headless
      - bin/godot_headless.64 --path game -s addons/gut/gut_cmdln.gd
