# https://taskfile.dev

version: '3'

tasks:
  edit:
    desc: edit game project
    cmds:
      - bin\\task.exe unzip:godot
      - bin\\godot.exe game\\project.godot

  gut:
    desc: run gut project using headless
    cmds:
      - bin\\task.exe unzip:godot
      - bin\\godot.exe --path game -s addons/gut/gut_cmdln.gd
